AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-service-database

  SAM Template for expense-service database

Resources:  
  ExpensePayer:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: ExpensePayer
      AttributeDefinitions: 
        - AttributeName: expenseId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema: 
        - AttributeName: expenseId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ExpensePayerStatus:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: ExpensePayerStatus
      AttributeDefinitions: 
        - AttributeName: expenseId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema: 
        - AttributeName: expenseId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  LeadingExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: LeadingExpense
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: transactionDateExpenseId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: transactionDateExpenseId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD

  ExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Expense
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD

  ExpenseGroupTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ExpenseGroup
      AttributeDefinitions:
        - AttributeName: parentExpenseId
          AttributeType: S
        - AttributeName: childExpenseId
          AttributeType: S
      KeySchema:
        - AttributeName: parentExpenseId
          KeyType: HASH
        - AttributeName: childExpenseId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD
      GlobalSecondaryIndexes:
        - IndexName: ChildExpenseIdIndex
          KeySchema:
            - AttributeName: childExpenseId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  UserExpenseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserExpense
      AttributeDefinitions:
        - AttributeName: expenseId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: expenseId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: expenseId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ExpenseConnectionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ExpenseConnection
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: expenseId
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
        - AttributeName: expenseId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD
      GlobalSecondaryIndexes:
        - IndexName: ExpenseIndex
          KeySchema:
            - AttributeName: expenseId
              KeyType: HASH
            - AttributeName: connectionId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ConnectionTokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ConnectionToken
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: expenseId
          AttributeType: S
      KeySchema:
        - AttributeName: expenseId
          KeyType: HASH
        - AttributeName: connectionId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD

  ExpenseItemTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ExpenseItem
      AttributeDefinitions:
        - AttributeName: expenseId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: expenseId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableClass: STANDARD