name: Deploy Production

on:
  release:
    types: [released]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_PROD }}
        aws-region: us-east-1

    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage production \
                --param="RTENV=production" \
                --param="QUEUE_STAGE_NAME=production" \
                --param="CONNECTION_TTL_SEC=1800" \
                --param="DB_REGION=us-east-1" \
                --param="DELETE_EXPIRED_INTERVAL_MIN=10080" \
                --param="DB_ENDPOINT=https://dynamodb.us-east-1.amazonaws.com/" \
                --param="APIG_URL=https://bybk9vinge.execute-api.us-east-1.amazonaws.com/production/" \
                --param="DevAccountId=${{ secrets.DEV_ACCOUNT_ID }}" \
                --param="StagingAccountId=${{ secrets.STAGING_ACCOUNT_ID }}" \
                --param="ProdAccountId=${{ secrets.PROD_ACCOUNT_ID }}" \
                --param="MESSAGE_QUEUE_ARN=${{ secrets.MESSAGE_QUEUE_ARN_PRODUCTION }}" \
                --param="FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_PRODUCTION }}" \
                --param="FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_PRODUCTION }}" \
                --param="FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_PRODUCTION }}" \
                --param="FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PRODUCTION }}" \
                --param="FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_PRODUCTION }}" \
                --param="FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_PRODUCTION }}" \
                --param="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }}" \
                --param="FIREBASE_ADMIN_CREDS=${{ secrets.FIREBASE_ADMIN_CREDS_JSON_PRODUCTION }}" \
                --param="RESOURCE_ACCOUNT_ID=${{ secrets.PROD_ACCOUNT_ID }}" \
                --param="DB_ACCESS_KEY_ID=${{ secrets.DB_ACCESS_KEY_ID_PROD }}" \
                --param="DB_SECRET_ACCESS_KEY=${{ secrets.DB_SECRET_ACCESS_KEY_PROD }}"

    - run: npm ci
      working-directory: ./resources/databases
    - run: sam build
      working-directory: ./resources/databases
    - run: |
        sam deploy --stack-name expense-service-database \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides "StagingLambdaExecutionRoleArn=${{ secrets.STAGING_EXPENSE_SERVICE_LAMBDA_EXECUTION_ROLE_ARN }}"
      working-directory: ./resources/databases

    - run: sam build
      working-directory: ./resources/topics
    - run: |
        sam deploy --stack-name expense-service-topics \
        --no-confirm-changeset \
        --no-fail-on-empty-changeset \
        --parameter-overrides \
            "DevAccountId=${{ secrets.DEV_ACCOUNT_ID }}" \
            "StagingAccountId=${{ secrets.STAGING_ACCOUNT_ID }}" \
            "ProdAccountId=${{ secrets.PROD_ACCOUNT_ID }}"
      working-directory: ./resources/topics

    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY_PROD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_PROD }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_PROD }}
