name: Deploy Staging

on:
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: actions/setup-python@v3
    - uses: aws-actions/setup-sam@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_STAGING }}
        aws-secret-access-key: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_STAGING }}
        aws-region: us-east-1

    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage staging \
                --param="RTENV=staging" \
                --param="QUEUE_STAGE_NAME=staging" \
                --param="CONNECTION_TTL_SEC=1800" \
                --param="DB_REGION=us-east-1" \
                --param="DELETE_EXPIRED_INTERVAL_MIN=10080" \
                --param="DB_ENDPOINT=https://dynamodb.us-east-1.amazonaws.com/" \
                --param="APIG_URL=https://i1nnpdkz89.execute-api.us-east-1.amazonaws.com/staging/" \
                --param="MESSAGE_QUEUE_ARN=${{ secrets.MESSAGE_QUEUE_ARN_STAGING }}" \
                --param="FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_PRODUCTION }}" \
                --param="FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_PRODUCTION }}" \
                --param="FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_PRODUCTION }}" \
                --param="FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_PRODUCTION }}" \
                --param="FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_PRODUCTION }}" \
                --param="FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_PRODUCTION }}" \
                --param="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_PRODUCTION }}" \
                --param="FIREBASE_ADMIN_CREDS=${{ secrets.FIREBASE_ADMIN_CREDS_JSON_PRODUCTION }}" \
                --param="RESOURCE_ACCOUNT_ID=${{ secrets.PROD_ACCOUNT_ID }}" \
                --param="messageQueueResourceName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/MessageQueue" \
                --param="connectionTokenTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ConnectionToken" \
                --param="connectionTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ExpenseConnection" \
                --param="expenseItemTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ExpenseItem" \
                --param="expensePayerTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ExpensePayer" \
                --param="expensePayerStatusTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ExpensePayerStatus" \
                --param="expenseTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/Expense" \
                --param="expenseGroupTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ExpenseGroup" \
                --param="expenseGroupChildIndexName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/ChildExpenseIdIndex" \
                --param="userExpenseTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/UserExpense" \
                --param="userExpenseUserIndexName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/UserIdIndex" \
                --param="leadingExpenseTableName=arn:aws:dynamodb:us-east-1:${{ secrets.PROD_ACCOUNT_ID }}:table/LeadingExpense"

    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY_STAGING }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID_STAGING }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY_STAGING }}
