name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage staging \
                --param="DB_EXPENSE_JOIN_REQUEST_TABLE_NAME=Splitsies-ExpenseJoinRequest-staging" \
                --param="CONNECTION_TTL_SEC=1800" \
                --param="DB_REGION=us-east-1" \
                --param="CONNECTION_TOKEN_TABLE_NAME=Splitsies-ConnectionToken-staging" \
                --param="CONNECTION_TABLE_NAME=Splitsies-ExpenseConnection-staging" \
                --param="TRANSACTION_DATE_INDEX_NAME=TransactionDateIndex" \
                --param="DELETE_EXPIRED_INTERVAL_MIN=10080" \
                --param="MESSAGE_QUEUE_RESOURCE_NAME=Splitsies-MessageQueue-staging" \
                --param="EXPENSE_UPDATE_TABLE_NAME=Splitsies-ExpenseUpdate-staging" \
                --param="DB_TABLE_NAME=Splitsies-Expense-staging" \
                --param="DB_ENDPOINT=https://dynamodb.us-east-1.amazonaws.com/" \
                --param="EXPENSE_ITEM_TABLE_NAME=Splitsies-ExpenseItem-staging" \
                --param="DB_USER_EXPENSE_TABLE_NAME=Splitsies-UserExpense-staging" \
                --param="APIG_URL=https://djb25cevxg.execute-api.us-east-1.amazonaws.com/staging/" \
                --param="PG_DATABASE_NAME=${{ secrets.PG_DATABASE_NAME_STAGING }}" \
                --param="PGPASSWORD=${{ secrets.PGPASSWORD }}" \
                --param="PG_HOST=${{ secrets.PG_HOST }}" \
                --param="PG_PORT=${{ secrets.PG_PORT }}" \
                --param="PGUSERNAME=${{ secrets.PGUSERNAME }}" \
                --param="INTERNAL_API_KEY=${{ secrets.INTERNAL_API_KEY }}" \
                --param="DB_ACCESS_KEY_ID=${{ secrets.DB_ACCESS_KEY_ID }}" \
                --param="DB_SECRET_ACCESS_KEY=${{ secrets.DB_SECRET_ACCESS_KEY }}" \
                --param="MESSAGE_QUEUE_ARN=${{ secrets.MESSAGE_QUEUE_ARN_STAGING }}" \
                --param="FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_STAGING }}" \
                --param="FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_STAGING }}" \
                --param="FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_STAGING }}" \
                --param="FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_STAGING }}" \
                --param="FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_STAGING }}" \
                --param="FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_STAGING }}" \
                --param="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_STAGING }}" \
                --param="FIREBASE_ADMIN_CREDS=${{ secrets.FIREBASE_ADMIN_CREDS_JSON_STAGING }}"
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY }}
