name: Deploy Dev PR

on:
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.1
      with:
        args: deploy --stage dev-pr \
                --param="DB_EXPENSE_JOIN_REQUEST_TABLE_NAME=Splitsies-ExpenseJoinRequest-dev-pr" \
                --param="CONNECTION_TTL_SEC=1800" \
                --param="DB_REGION=us-east-1" \
                --param="CONNECTION_TOKEN_TABLE_NAME=Splitsies-ConnectionToken-dev-pr" \
                --param="CONNECTION_TABLE_NAME=Splitsies-ExpenseConnection-dev-pr" \
                --param="TRANSACTION_DATE_INDEX_NAME=TransactionDateIndex" \
                --param="DELETE_EXPIRED_INTERVAL_MIN=10080" \
                --param="MESSAGE_QUEUE_RESOURCE_NAME=Splitsies-MessageQueue-dev-pr" \
                --param="EXPENSE_UPDATE_TABLE_NAME=Splitsies-ExpenseUpdate-dev-pr" \
                --param="DB_TABLE_NAME=Expense-dev-pr" \
                --param="DB_ENDPOINT=https://dynamodb.us-east-1.amazonaws.com/" \
                --param="EXPENSE_ITEM_TABLE_NAME=Splitsies-ExpenseItem-dev-pr" \
                --param="DB_USER_EXPENSE_TABLE_NAME=Splitsies-UserExpense-dev-pr" \
                --param="APIG_URL=https://srzam2rrj5.execute-api.us-east-1.amazonaws.com/dev-pr/" \
                --param="PG_DATABASE_NAME=${{ secrets.PG_DATABASE_NAME_DEV_PR }}" \
                --param="PGPASSWORD=${{ secrets.PGPASSWORD }}" \
                --param="PG_HOST=${{ secrets.PG_HOST }}" \
                --param="PG_PORT=${{ secrets.PG_PORT }}" \
                --param="PGUSERNAME=${{ secrets.PGUSERNAME }}" \
                --param="INTERNAL_API_KEY=${{ secrets.INTERNAL_API_KEY }}" \
                --param="DB_ACCESS_KEY_ID=${{ secrets.DB_ACCESS_KEY_ID }}" \
                --param="DB_SECRET_ACCESS_KEY=${{ secrets.DB_SECRET_ACCESS_KEY }}" \
                --param="MESSAGE_QUEUE_ARN=${{ secrets.MESSAGE_QUEUE_ARN_DEV_PR }}" \
                --param="FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_DEV_PR }}" \
                --param="FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_DEV_PR }}" \
                --param="FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_DEV_PR }}" \
                --param="FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_DEV_PR }}" \
                --param="FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_DEV_PR }}" \
                --param="FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_DEV_PR }}" \
                --param="FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_DEV_PR }}" \
                --param="FIREBASE_ADMIN_CREDS=${{ secrets.FIREBASE_ADMIN_CREDS_JSON_DEV_PR }}" \
                --param="RTENV=dev-pr" \                
                --param="QUEUE_STAGE_NAME=devpr"

      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.SPLITSIES_DEPLOY_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPLITSIES_DEPLOY_SECRET_KEY }}
